version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: calcom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: calcom
      POSTGRES_USER: calcom
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-calcom123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calcom-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calcom -d calcom"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: calcom-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - calcom-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Cal.com Web Application
  calcom-web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - DATABASE_URL=postgresql://calcom:${POSTGRES_PASSWORD:-calcom123}@postgres:5432/calcom
        - DATABASE_DIRECT_URL=postgresql://calcom:${POSTGRES_PASSWORD:-calcom123}@postgres:5432/calcom
      target: production
    container_name: calcom-web
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://calcom:${POSTGRES_PASSWORD:-calcom123}@postgres:5432/calcom
      DATABASE_DIRECT_URL: postgresql://calcom:${POSTGRES_PASSWORD:-calcom123}@postgres:5432/calcom
      
      # App Configuration
      NEXT_PUBLIC_WEBAPP_URL: ${WEBAPP_URL:-http://localhost:3000}
      NEXTAUTH_URL: ${WEBAPP_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-super-secret-nextauth-key-change-this}
      CALENDSO_ENCRYPTION_KEY: ${ENCRYPTION_KEY:-your-32-character-encryption-key}
      
      # Email Configuration
      EMAIL_FROM: ${EMAIL_FROM:-noreply@yourdomain.com}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST:-smtp.gmail.com}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT:-465}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      
      # Optional: SendGrid
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_EMAIL: ${SENDGRID_EMAIL}
      
      # Redis (for session storage and caching)
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      
      # Application Settings
      NEXT_PUBLIC_TEAM_IMPERSONATION: ${TEAM_IMPERSONATION:-false}
      NEXT_PUBLIC_AVAILABILITY_SCHEDULE_INTERVAL: ${SCHEDULE_INTERVAL:-15}
      
      # Cron Settings
      CRON_API_KEY: ${CRON_API_KEY:-your-cron-api-key}
      CRON_ENABLE_APP_SYNC: ${CRON_ENABLE_APP_SYNC:-false}
      
      # Security
      NODE_ENV: production
      
      # Optional: Analytics
      NEXT_PUBLIC_TELEMETRY_KEY: ${TELEMETRY_KEY}
      
      # Optional: License
      NEXT_PUBLIC_LICENSE_CONSENT: ${LICENSE_CONSENT:-agree}
      
    ports:
      - "3000:3000"
    networks:
      - calcom-network
    volumes:
      - app_data:/app/apps/web/public/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Database administration tool (optional)
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.studio
    container_name: calcom-studio
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://calcom:${POSTGRES_PASSWORD:-calcom123}@postgres:5432/calcom
    ports:
      - "5555:5555"
    networks:
      - calcom-network
    profiles:
      - tools

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: calcom-nginx
    restart: unless-stopped
    depends_on:
      - calcom-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - calcom-network
    profiles:
      - proxy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_data:
    driver: local

networks:
  calcom-network:
    driver: bridge
